### ISSUE TITLE
PYCEF not parsing some logs correctly

### ISSUE THREAD

**Issue by anuj-agarwal** [DavidJBianco/pycef#13]
Check the below log format: The 5th and 6th placeholder has 'value\|value' passed and the pycef parser breaks at that cases.
CEF:0|value|value||value\|value|value\|value|value| col1=value1

We were able to check this and modify three lines of code which makes it more robust for such cases and works well with the correctly formatted logs.

Please find attached the jpg representing the changes made.
Hope this will be useful for your team and others as well.

![pycef_changes](https://user-images.githubusercontent.com/34479209/56785967-e27d2e00-6814-11e9-9e29-ed60ba51367e.jpg)

**Comment by punkrokk** [comment]
@anuj-agarwal want to submit a PR?

**Comment by DavidJBianco** [comment]
The sample log is not correctly formatted (the _DeviceVersion_ field is missing).  I don't think the answer is to change the parser, since once we know the format is invalid, we're just guessing what the remaining fields represent.

I think the better answer would be to validate that the mandatory header fields are all present, and log a warning if they're not.  We already do this if the input string doesn't appear to be CEF, but the validation we use doesn't cover this case.  

I'll update the code and include a test case for it.

**Comment by punkrokk** [comment]
Yea I agree. Cool!

**Comment by DavidJBianco** [comment]
This is resolved in 7fe1b00 and published as v1.11.
